on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  GoodJob:
    runs-on: 'ubuntu-latest'
    steps:
      - name: github event
        run: echo "${{ toJson(github.event) }}"
      - name: print length of commits
        run: |
          echo "${{ toJson(github.event.commits) }}" > commits.json
          length=$(cat commits.json | jq length)
          echo "github.events.commits length = $length"
