on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  GoodJob:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: print length of commits
        run: | 
          commits=$(echo '${{ toJSON(github.event.commits) }}' | jq -r)
          read commits_length <<< $(.github/workflows/commits_count.sh '$commits' )
  
