on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  GoodJob:
    runs-on: 'ubuntu-latest'
    steps:
      - name: print length of commits
        id: changelog
        uses: actions/github-script@v6.3.1
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
        with:
          script: |
            const commits = JSON.parse(process.env.COMMITS);
            var length = 0;
            for (const commit of commits) {
             length += 1;
            }
            console.log(length);
 