on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  GoodJob:
    runs-on: 'ubuntu-latest'
    steps:
      - name: print gihub.event stuff
        run: |
          ${{ toJson(github.event.commits) }} > commits.json
          length=$(cat commits.json | jq length)
          echo "github.events.commits length = $length"
