on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  GoodJob:
    runs-on: 'ubuntu-latest'
    steps:
      - name: print length of commits
        run: |
          commits=$(echo '${{ toJSON(github.event.commits) }}' | jq -r)
          echo "$commits"
          read commits_length <<< $(.github/workflows/commits_count.sh $commits )
  
