on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  GoodJob:
    runs-on: 'ubuntu-latest'
    steps:
      - name: print length of commits
        run: |
          $length=0
          $commits = ${{ github.event.commits }}
          foreach ($commit in $commits) {
            $length+=1
          }
          echo "github.events.commits length = $length"