on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  GoodJob:
    runs-on: 'ubuntu-latest'
    steps:
      - name: print gihub.event stuff
        run: |
          echo "event_name  = ${{ toJson(github.event_name) }}"
          echo "github.events.commits = ${{ toJson(github.event.commits) }}"