on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  GoodJob:
    runs-on: 'ubuntu-latest'
    steps:
      - name: print gihub.event stuff
        run: |
          length=${{ github.event.commits }} | jq length
          echo "github.events.commits length = $length"
